version: "3"

services:
  app:
    build:
      dockerfile: ./
      context: ./
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://postgres:postgres@0.0.0.0:5432/ejer_final
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ejer_final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres