pipeline {
    agent any
    environment {
        POSTGRES_DB = 'ejer_final'
        POSTGRES_USER = 'juan'
        POSTGRES_PASSWORD = 'juan'
    }
    stages {
        stage('Iniciar contenedor de PostgreSQL') {
            steps {
                script {
                    // Crear red de Docker
                    def network = docker.network('mi-red')

                    // Iniciar contenedor de PostgreSQL conectado a la red
                    def postgresContainer = docker.image('postgres:latest').run(
                        "--network=mi-red -p 5432:5432 -e POSTGRES_DB=${POSTGRES_DB} -e POSTGRES_USER=${POSTGRES_USER} -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
                    )
                }
            }
        }
        stage('Iniciar contenedor con Python y app') {
            steps {
                script {
                    // Esperar a que PostgreSQL esté listo
                    sh 'dockerize -wait tcp://localhost:5432 -timeout 1m'

                    // Iniciar contenedor de la aplicación conectado a la misma red
                    def appContainer = docker.image('tu/imagen:tag').run("--network=mi-red")

                    // Esperar a que la aplicación esté lista (ajusta según tus necesidades)
                    sh 'sleep 10'

                    // Ejecutar curl después de esperar
                    sh 'curl http://localhost:5000/data'
                }
            }
        }
    }
    post {
        always {
            // Detener y eliminar los contenedores después de la ejecución del pipeline
            script {
                postgresContainer.stop()
                postgresContainer.remove(force: true)
                appContainer.stop()
                appContainer.remove(force: true)
            }
            echo "Fin del pipeline"
        }
    }
}
