name: Python CI

on:
  push:
    branches: [Dev]
  pull_request:
    branches: [Dev]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: 'ejer_final'
          POSTGRES_USER: 'juan'
          POSTGRES_PASSWORD: 'juan'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ajusta según tus necesidades

    - name: Run tests
      run: |
        python --version
        sh manage.sh
        python run.py
        python pytest ./QA/tests
        python pytest --cov=app ./QA/tests
