name: Python CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: 'ejer_final'
          POSTGRES_USER: 'juan'
          POSTGRES_PASSWORD: 'juan'  # Asegúrate de que esta contraseña sea correcta
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Wait for PostgreSQL
      run: sleep 10  # Esperar 10 segundos para que PostgreSQL se inicie completamente

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ajusta según tus necesidades

    - name: Run app
      run: |
        python manage.py
        python run.py
        python --version
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Juan"}' http://localhost:5000/data
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Pedro"}' http://localhost:5000/data
        curl -X POST -H "Content-Type: application/json" -d '{"name": "Luis Manuel"}' http://localhost:5000/data
        curl http://localhost:5000/data
        curl -X DELETE http://localhost:5000/data/1
